### ISSUE TITLE
Subsecond time-stamp in docker logger driver for stderr

### ISSUE THREAD

**Issue by antoniosoftcr** [fluent/fluent-logger-golang#35]
Hi

I would like to if it is possible that sub-second precision time-stamp on stderr would be added to this driver.

**Comment by YerisAntonio** [comment]
This is an example from docker logs -t, those lines have really precise timestamp, but none are sent to by the logger driver:

`2016-07-21T14:50:03.872614398Z Starting Monit 5.17.1 daemon with http interface at [localhost]:2812
2016-07-21T14:50:15.797180785Z {"name":"Logger","hostname":"257d35137014","pid":14,"level":30,"msg":"initializing api twitter","time":"2016-07-21T14:50:15.520Z","v":0}
2016-07-21T14:50:17.760994676Z /usr/src/app/node_modules/bluebird/js/release/async.js:61
2016-07-21T14:50:17.761024450Z         fn = function () { throw arg; };
2016-07-21T14:50:17.761028615Z                            ^
2016-07-21T14:50:17.761032552Z 
2016-07-21T14:50:17.761038010Z ReferenceError: serviceName is not defined
2016-07-21T14:50:17.761043498Z     at /usr/src/app/node_modules/@sbr/service/lib/server/consulWrapper.js:35:34
2016-07-21T14:50:17.761049527Z     at next (native)
2016-07-21T14:50:17.761053326Z     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
2016-07-21T14:50:17.761059775Z     at PromiseSpawn._promiseFulfilled (/usr/src/app/node_modules/bluebird/js/release/generators.js:97:49)
2016-07-21T14:50:17.761063422Z     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:566:26)
2016-07-21T14:50:17.761066899Z     at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:606:10)
2016-07-21T14:50:17.761070334Z     at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:685:18)
2016-07-21T14:50:17.761073706Z     at Async._drainQueue (/usr/src/app/node_modules/bluebird/js/release/async.js:138:16)
2016-07-21T14:50:17.761077094Z     at Async._drainQueues (/usr/src/app/node_modules/bluebird/js/release/async.js:148:10)
2016-07-21T14:50:17.761080583Z     at Immediate.Async.drainQueues [as _onImmediate] (/usr/src/app/node_modules/bluebird/js/release/async.js:17:14)
2016-07-21T14:50:17.761084072Z     at processImmediate [as _immediateCallback] (timers.js:383:17)
2016-07-21T14:50:17.797352776Z {"name":"Logger","hostname":"257d35137014","pid":14,"level":30,"msg":"initializing api events twitter","time":"2016-07-21T14:50:15.523Z","v":0}
2016-07-21T14:50:17.797380254Z {"name":"Logger","hostname":"257d35137014","pid":14,"level":30,"msg":"event registered twitter.create","time":"2016-07-21T14:50:15.523Z","v":0}
`

**Comment by zerthimon** [comment]
+1

**Comment by redlolgeerf** [comment]
+1

**Comment by tagomoris** [comment]
Note: [Using Extensions with tinylib/msgp](https://github.com/tinylib/msgp/wiki/Using-Extensions)

**Comment by ypjin** [comment]
It's one year later. Any update on this? Thanks a lot!
